spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: stable-route
          uri: http://localhost:8081
          predicates:
            - Weight=resource-group,90
        - id: canary-route
          uri: http://localhost:8082
          predicates:
            - Weight=resource-group,10

